services:
  web:
    build: web_server_fe
    restart: on-failure:3
    volumes:
      - shared-images-volume:/usr/share/nginx/html/images
    ports:
      - 8080:80
    depends_on:
      - lobby

  lobby:
    build: web_server_lobby
    restart: on-failure:3
    volumes:
      - shared-images-volume:/workdir/images
    ports:
      - 5000:5000
    depends_on:
      - diffusion_server
    networks:
      - redis_net

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - redis_net

networks:
  redis_net:
    driver: bridge
