FROM node as build-stage

COPY ./fe /workdir
WORKDIR /workdir

ENV NODE_ENV=production

# Install node
RUN npm ci
RUN npm run build

FROM nginx
COPY default.conf /etc/nginx/conf.d/
COPY --from=build-stage /workdir/dist/ /usr/share/nginx/html